---
- name: gather system information
  hosts: vms
  vars:
    - title: "Automated Gathered System Information"
    - cols: 
      - "HOSTNAME"
      - "CPU"
      - "MEMORY"
      - "DISK_PARTITION"
#    - cols: { col1: "hostname", col2: "ansible_processor_cores", col3: "ansible_memtotal_mb" }

  tasks:
    - name: print hostname
      debug:
        var: ansible_hostname
    - name: gather df info
      shell: df | grep sda
      register: info_df
    - name: set info_df
      set_fact:
        info_df: "{{ info_df.stdout_lines }}"
    - name: create html report
      template:
        src: report.html.j2
        dest: /home/vagrant/playbook/result.html
      delegate_to: 127.0.0.1
      run_once: yes
