apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: alex-kube
  region: ap-northeast-2
managedNodeGroups:
  - name: ondemand-workers
    labels:
      lifecycle: ondemand
    minSize: 2
    maxSize: 5
    instanceType: t3.medium
    desiredCapacity: 3
