---
- name: set fact from csv
  hosts: localhost
  vars:
    csv_filename: csv.txt
  tasks:
    - name: set variables
      set_fact:
        "{{ lookup('csvfile', item + ' file=' + csv_filename + ' col=0 delimiter=,') }}": "{{ lookup('csvfile', item + ' file=' + csv_filename + ' col=1 delimiter=,') }}"
      with_lines: /usr/bin/awk -F',' '!/^#/ && !/^$/ { print $1 }' {{ csv_filename}}
    - name: debug var
      debug:
        var: key1
